blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeletelView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delite/<int:pk>/', BlogDeletelView.as_view(), name='blog_delete')
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='usersf')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}

class Blog(models.Model):
    title = models.CharField(max_length=60, verbose_name="Заголовок", help_text="Введите заголовок", default=None)
    slug = models.CharField(max_length=60, verbose_name="slug", help_text="Введите slug", **NULLABLE)
    content = models.TextField(verbose_name="Текст", help_text="Введите текст", **NULLABLE)
    photo = models.ImageField(upload_to="blogs/", verbose_name="Фото", help_text="Загрузите фото", **NULLABLE)
    created_at = models.DateField(verbose_name="Дата создания", help_text="Укажите дату создания", **NULLABLE)
    is_published = models.BooleanField(verbose_name="Публикация", help_text="Укажите статус публикации", default=True, **NULLABLE)
    views_count = models.IntegerField(verbose_name="Просмотры",help_text="Количество просмотров", default=0, **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = (
        "title", "content", "photo",
        "created_at", "is_published"
    )
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = (
        "title", "content", "photo",
        "created_at", "is_published"
    )

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeletelView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>
    <p class="lead">Удалить статью</p>
</div>
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить статью "{{ object.title }}" ?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'blog:blog_list' %}" class="btn btn-primary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Подробно</h1>
</div>

<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-3">
                <img src="{{ object.photo|media_filter }}" class="img-fluid" alt="...">
            </div>
            <div class="col-8">
                <div class="card-body">
                    <h4 class="card-title">{{ object.title }} ({{ object.slug }})</h4>
                    <p class="card-text">Текст: {{ object.content }}</p>
                    <p class="card-text">Дата создания: {{ object.created_at }}</p>
                </div>
            </div>
            <div class="card-footer mt-3">
                Просмотры {{ object.views_count }}
            </div>
            <div class="col-3 mx-auto">
                <a href="{% url 'blog:blog_list' %}" class="btn btn-primary mt-3">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>
    <p class="lead">
        {% if not object %}
        Добавить статью
        {% else %}
        Изменить статью
        {% endif %}
    </p>
</div>
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if not object %}
                                Создать
                                {% else %}
                                Изменить
                                {% endif %}
                            </button>
                            <a href="{% url 'blog:blog_list' %}" class="btn btn-primary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>
    <p class="lead">Блог - статьи для обсуждений</p>
</div>
<div class="container">
    <div class="row text-center">
        <div class="col-lg-12 col-md-6 col-sm-12">
             <a href="{% url 'blog:blog_create' %}" class="btn btn-primary">Добавить статью</a>
        </div>
    </div>
</div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4 mt-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ object }}</h4>
                    <p class="card-text">
                        {{ object.content|slice:100 }}
                    </p>
                    <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-primary">Посмотреть</a>
                    <a href="{% url 'blog:blog_edit' object.pk %}" class="btn btn-primary">Редактировать</a>
                    <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-primary">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}