blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeletelView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delite/<int:pk>/', BlogDeletelView.as_view(), name='blog_delete')
    ]

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import HomeTemplateView, ContactsView, ProductListView, ProductDitailView, ProductUpdateView, \
    ProductDeleteView, ProductCreateView, VersionListView, VersionCreateView, VersionUpdateView, VersionDetailView, \
    VersionDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
                  path('', HomeTemplateView.as_view(), name='home'),
                  path('contacts/', ContactsView.as_view(), name='contacts_list'),
                  path('detail/<int:pk>/', cache_page(60)(ProductDitailView.as_view()), name='product_detail'),
                  path('home/list/', ProductListView.as_view(), name='product_list'),
                  path('catalog/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
                  path('catalog/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
                  path('catalog/create/', ProductCreateView.as_view(), name='product_form'),
                  path('versions/<int:pk>', VersionListView.as_view(), name='versions'),
                  path('version/', VersionCreateView.as_view(), name='version_create'),
                  path('version/<int:pk>/update/', VersionUpdateView.as_view(), name='version_update'),
                  path('version/<int:pk>', VersionDetailView.as_view(), name='version_detail'),
                  path('versions/<int:pk>/delete/', VersionDeleteView.as_view(), name='version_delete'),
                  path('categories/', CategoryListView.as_view(), name='categories'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='usersf')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    name_category = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание категории')

    def __str__(self):
        return f'{self.name_category} {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'



class Product(models.Model):
    name_product = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание продукта')
    preview = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    create_at = models.DateField(verbose_name='дата создания')
    update_at = models.DateField(verbose_name='дата последнего изменения')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')


    def __str__(self):
        return f'{self.name_product} {self.description} {self.category}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            (
                'set_published_product',
                'Can set published product'
            ),
            (
                'change_description_product',
                'Can change description product'
            ),
            (
                'change_category',
                'Can change category'
            ),
        ]


class Contacts(models.Model):
    city = models.CharField(max_length=50, verbose_name="Страна")
    identity_nalog_number = models.IntegerField(verbose_name="ИНН")
    address = models.TextField(verbose_name="Адрес")
    slug = models.CharField(max_length=255, verbose_name="URL", **NULLABLE)

    def __str__(self):
        return f"{self.city} {self.identity_nalog_number} {self.address}"

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"




class Version(models.Model):

    """Модель версия продукта"""
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE, related_name='versions', **NULLABLE)
    number_v = models.PositiveIntegerField(verbose_name='номер версии')
    name_version = models.CharField(max_length=100, verbose_name='название версии')
    current_version = models.BooleanField(default=True, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name_version} - {self.number_v}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django.db.models import BooleanField
from django.forms import ModelForm, forms
from catalog.models import Product, Version


class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'current_version':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleMixin, ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('created_at', 'updated-at', 'owner')

    def clean_name_product(self):
        cleaned_data = self.cleaned_data['name_product']
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in bad_words:
            if word in cleaned_data:
                raise forms.ValidationError(f'Недопустимое слово: {word}')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in bad_words:
            if word in cleaned_data:
                raise forms.ValidationError(f'Недопустимое слово: {word}')

        return cleaned_data



class ProductModeratorForm(StyleMixin, ModelForm):
    class Meta:
        model = Product
        fields = ['name_product', 'description', 'category']


class VersionForm(StyleMixin, ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
#from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, CreateView, DeleteView, UpdateView
from django.forms import inlineformset_factory
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Contacts, Version, Category
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.services import get_categories_from_cache

class ContactsView(ListView):
    model = Contacts
    extra_context = {'title': 'Контакты'}
    template_name = 'catalog/contacts_list.html'


class ProductDitailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    extra_context = {'title': 'Продукты на любой вкус'}



class HomeTemplateView(TemplateView):
    template_name = "catalog/home.html"



class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_from.html'
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить продукт'
        return context

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    template_name = 'catalog/product_from.html'
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context['formset'] = ProductFormset(instance=self.object)
        context['title'] = 'Изменить продукт'
        return context

    def form_valid(self, form: ProductForm):

        context = self.get_context_data()
        versions_formset = context.get('formset')

        self.object = form.save()

        if versions_formset:
            if versions_formset.is_valid():
                versions_formset.instance = self.object
                versions_formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm('product.set_published_product')
                and user.has_perm('product.change_description_product')
                and user.has_perm('product.change_category')):
            return ProductModeratorForm
        else:
            return PermissionDenied




class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удалить продукт'
        return context




class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = Product.objects.all()

        for product in products:
            versions = Version.objects.filter(product=product)
            active_versions = versions.filter(current_version=True)
            if active_versions:
                product.name_version = active_versions.last().name_version
                product.number_version = active_versions.last().number_v
        context_data['object_list'] = products
        return context_data


class VersionListView(ListView):
    model = Version

    def get_queryset(self, *args, **kwargs):
        queryset = Version.objects.all()
        products = Product.objects.all()
        for product in products:
            print(product)
            versions = Version.objects.filter(product=product)
            # print(queryset.product == product)
            return versions
        return Version.objects.filter(product=Product.objects.get(pk=self.kwargs.get('pk')))

class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:product_list')


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:product_list')


class VersionDetailView(DetailView):
    model = Version
    template_name = "catalog/version_detail.html"


class VersionDeleteView(DeleteView):
    model = Version
    success_url = reverse_lazy('catalog:product_list')
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name_version'] = 'Удалить версию'
        return context



class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_categories_from_cache()

catalog/templates/catalog/category_list.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <p>Называние: {{ object.name_category }}</p>
                <p>Описание: {{ object.description|slice:100 }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/detail_product.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name_product }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} RUB</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Описание: {{ object.description }}</li>
                        <li>- Категория: {{ object.category }}</li>
                        <li>- Дата создания: {{ object.create_at }}</li>
                        <li>- Дата изменения: {{ object.update_at }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Menu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Магазин продуктов: "У дома"</h1>
    <p class="lead">У нас вы можете приобрести любые продукты на ваш вкус
        </p>
</div>




<div class="container col-12">

{% block content %}
{% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a href="{% url 'catalog:contacts_list' %}" class="btn btn-primary btn-lg mt-3">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">{{ title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-6">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <p> Хотите удалить запись "{{ object.title }}"? </p>
                                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подтвердить</button>

                                        </form>
                                        <a href="{% url 'catalog:product_list' %}" class="btn btn-lg btn-block btn-outline-primary">Отмена</a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name_product }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} RUB</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Описание: {{ object.description }}</li>
                        <li>- Категория: {{ object.category }}</li>
                        <li>- Дата создания: {{ object.create_at }}</li>
                        <li>- Дата изменения: {{ object.update_at }}</li>
                        <div class="btn-group">
                            <a type="button" href="{% url 'catalog:version_create' %}"
                               class="btn btn-lg btn-block btn-outline-primary">Добавить версию продукта</a>
                            {% if product.versions.exists %}
                            <a type="button" href="{% url 'catalog:versions' object.pk %}"
                               class="btn btn-lg btn-block btn-outline-primary">Просмотр версий</a>
                            {% endif %}
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
{% csrf_token %}
<div class="container col-12">
    {% csrf_token %}
    {% if user.is_authenticated %}
    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
       href="{% url 'catalog:product_form' %}">
        Добавить запись</a>
    {% endif %}
    <div class="row text-center col-12">
        {% for product in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name_product }}</h4>
                </div>
                <img src="{{ product.preview | media_filter}}">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.price }} RUB</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Описание: {{ product.description|slice:100 }}...</li>
                        <li>- Категория: {{ product.category }}</li>
                        <li>- Дата создания: {{ product.create_at }}</li>
                        <li>- Дата изменения: {{ product.update_at }}</li>
                        <div>
                            {% if product.versions.exists %}
                            <p>Версия {{ product.name_version }}</p>
                            <p>Номер версии {{ product.number_version }}</p>
                            {% endif %}
                        </div>
                    </ul>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product_detail' product.pk %}">
                        Подробнее
                    </a>
                    {% if user == object.owner or perms.product.set_published_product and perms.product.change_description_product and perms.product.change_category %}
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product_update' product.pk %}">
                        Изменить
                    </a>
                    {% endif %}
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product_delete' product.pk %}">
                        Удалить
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/products_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
{% csrf_token %}
<div class="container col-12">
    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                                    href="{% url 'catalog:product_form' %}">
                                    Добавить запись</a>
    <div class="row text-center col-12">
        {% for product in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name_product }}</h4>
                </div>
                <img src="{{ product.preview | media_filter}}">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.price }} RUB</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Описание: {{ product.description|slice:100 }}...</li>
                        <li>- Категория: {{ product.category }}</li>
                        <li>- Дата создания: {{ product.create_at }}</li>
                        <li>- Дата изменения: {{ product.update_at }}</li>
                    </ul>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'catalog:product_detail' product.pk %}">
                                Подробнее
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'catalog:product_update' product.pk %}">
                                Изменить
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'catalog:product_delete' product.pk %}">
                                Удалить
                            </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/version_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"></h1>
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Удаление</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-lg btn-outline-danger">
                                Удалить версию: {{ object.name_version }} ?
                            </button>
                            <a type="submit" class="btn btn-lg btn-outline-primary"
                               href="{% url 'catalog:product_list' %}">Отмена
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/version_detail.html
{% extends 'catalog/home.html' %}
{% block content %}
    <div class="card-body">
        <h1 class="card-title pricing-card-title">{{ object.name_version }}</h1>
        <h2 class="card-title pricing-card-title">{{ object.number_v }}</h2>
        <div class="btn-group">
            <a type="button" href="{% url 'catalog:product_list' %}" class="btn btn-lg btn-block btn-outline-primary">Назад</a>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/version_list.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <div>
                        <p>Версия {{ object.name_version}}</p>
                        <p>Номер версии {{ object.number_v }}</p>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'catalog:version_detail' pk=object.pk %}" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                            <a href="{% url 'catalog:version_update' pk=object.pk %}" class="btn btn-sm btn-outline-secondary">Редактирование</a>
                            <a href="{% url 'catalog:version_delete' pk=object.pk %}" class="btn btn-sm btn-outline-danger">Удаление</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}